### ISSUE TITLE
PT100 Problems

### ISSUE THREAD

**Issue by KenCope** [Manuel83/craftbeerpi-plugins#6]
I have my MAX31865 boards hooked up.  All read the same temp...1800F whether the PT100 is plugged in or not.  I have checked all connections and did not find a short.  Anybody have any ideas??  3-wire RTD.

Thanks.

**Comment by ksullivan86** [comment]
That's a fault code i found this out with a faulty board and also a faulty sensor.
Also -4?? (I can't remember the last 2 digets) is given when no sensor is attached.

**Comment by motocamp** [comment]
Did you short-circuit F- and RTD-? Just connect the white cable then with RTD- and the two red cables with RTD+ and F+.
